config/routes.rb
Rails.application.routes.draw do
  resources :shows

  devise_for :users

  root 'homes#index'
  
  resources :members

  get '/shows', to: 'homes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/show.rb
class Show < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
  	if current_user
  		@currentUser = current_user
  	end

  	@shows = Show.all
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy], notice: 'Please log in with an admin account.'
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
    @currentUser = current_user
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:name, :role, :image, :bio, :dateJoined, :dateModified)
    end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy], notice: 'Please log in with an admin account.'
  before_action :set_show, only: [:show, :edit, :update, :destroy]

  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.all.order(:dateOfShow);
    @currentUser = current_user
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def show_params
      params.require(:show).permit(:title, :location, :streetAddress1, :streetAddress2, :city, :state, :zipcode, :dateOfShow, :locationURL, :imageLocation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/layouts/_admin_header.html.erb
<div class="admin-header">
	<p>Welcome <%= @currentUser.email %>
	<%= link_to "Log Out", destroy_user_session_path, :method => :delete %></p>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
	<p>Copyright &copy;2020 Mandi Gunningham </p>
</div>

app/views/layouts/_gigs.html.erb
<div class="gigs">
	<h1>Upcoming Gigs</h1>
	<% @shows.each do |show| %>
		<div class="ind-gig">
			<h3><%= show.title %></h3>
			<a href=<%= show.locationURL %>><%= show.location %></a><br>
			<span class="date"><%= show.dateOfShow %></span>
			<% if @currentUser %>
	          <td><%= link_to 'Show', show %></td>
	          <td><%= link_to 'Edit', edit_show_path(show) %></td>
	          <td><%= link_to 'Delete', show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	        <% end %>
		</div>
	<% end %>

	<%if @currentUser %>
	  <%= link_to 'New Show', new_show_path %>
	<% end %>
</div>

app/views/layouts/_header.html.erb
<% if @currentUser %>
	<%= render 'layouts/admin_header' %>
<% end %>
<div class="header">
	<div class="header-title">
		<h1>Barefoot Nina</h1>
	</div>

	<ul class="nav">
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Member Bios", members_path %></li>
		<li><%= link_to "Music Samples", root_path %></li>
		<li><%= link_to "Photos", root_path %></li>
		<li><%= link_to "Book Us!", root_path %></li>
	</ul>
</div>
<div class="clear"></div>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BarefootNinaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= render 'layouts/header' %>
    <div class="wrapper">
      <%= yield %>
    </div>
    <div class="clear"></div>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_field :bio %>
  </div>

  <div class="field">
    <%= form.label :dateJoined %>
    <%= form.datetime_select :dateJoined %>
  </div>

  <div class="field">
    <%= form.label :dateModified %>
    <%= form.datetime_select :dateModified %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to "Home", root_path %>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th>Image</th>
      <th>Bio</th>
      <th>Datejoined</th>
      <th>Datemodified</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.role %></td>
        <td><%= member.image %></td>
        <td><%= member.bio %></td>
        <td><%= member.dateJoined %></td>
        <td><%= member.dateModified %></td>
        <% if @currentUser %>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Delete', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @currentUser %>
<%= link_to 'New Member', new_member_path %>
<% end %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @member.role %>
</p>

<p>
  <strong>Image:</strong>
  <%= @member.image %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @member.bio %>
</p>

<p>
  <strong>Datejoined:</strong>
  <%= @member.dateJoined %>
</p>

<p>
  <strong>Datemodified:</strong>
  <%= @member.dateModified %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/shows/_form.html.erb
<%= form_with(model: show, local: true) do |form| %>
  <% if show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
        <% show.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :streetAddress1 %>
    <%= form.text_field :streetAddress1 %>
  </div>

  <div class="field">
    <%= form.label :streetAddress2 %>
    <%= form.text_field :streetAddress2 %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode %>
  </div>

  <div class="field">
    <%= form.label :dateOfShow %>
    <%= form.datetime_select :dateOfShow %>
  </div>

  <div class="field">
    <%= form.label :locationURL %>
    <%= form.text_field :locationURL %>
  </div>

  <div class="field">
    <%= form.label :imageLocation %>
    <%= form.text_field :imageLocation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to "Home", root_path %>

<h1>Shows</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th>Streetaddress1</th>
      <th>Streetaddress2</th>
      <th>City</th>
      <th>State</th>
      <th>Zipcode</th>
      <th>Dateofshow</th>
      <th>Locationurl</th>
      <th>Imagelocation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shows.each do |show| %>
      <tr>
        <td><%= show.title %></td>
        <td><%= show.location %></td>
        <td><%= show.streetAddress1 %></td>
        <td><%= show.streetAddress2 %></td>
        <td><%= show.city %></td>
        <td><%= show.state %></td>
        <td><%= show.zipcode %></td>
        <td><%= show.dateOfShow %></td>
        <td><%= show.locationURL %></td>
        <td><%= show.imageLocation %></td>
        <% if @currentUser %>
          <td><%= link_to 'Show', show %></td>
          <td><%= link_to 'Edit', edit_show_path(show) %></td>
          <td><%= link_to 'Destroy', show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%if @currentUser %>
  <%= link_to 'New Show', new_show_path %>
<% end %>

app/views/shows/new.html.erb
<h1>New Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @show.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @show.location %>
</p>

<p>
  <strong>Streetaddress1:</strong>
  <%= @show.streetAddress1 %>
</p>

<p>
  <strong>Streetaddress2:</strong>
  <%= @show.streetAddress2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @show.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @show.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @show.zipcode %>
</p>

<p>
  <strong>Dateofshow:</strong>
  <%= @show.dateOfShow %>
</p>

<p>
  <strong>Locationurl:</strong>
  <%= @show.locationURL %>
</p>

<p>
  <strong>Imagelocation:</strong>
  <%= @show.imageLocation %>
</p>

<%= link_to 'Edit', edit_show_path(@show) %> |
<%= link_to 'Back', shows_path %>